### PR TITLE
Read temperatures presets from manufacturer pkg

### LINKED ISSUE #450: Manufacturers should be able to define material temperatures pre-sets
Manufacturers should be able to define in their manufacturer package which materials and temperatures

screen shot 2018-11-14 at 4 10 30 pm

### PR DESCRIPTION
**Pull request by julianCast**
- Manufacturer will only need to add his temp_presets to its definition.yaml file.

Closes #450

### CODE REVIEW

**Comment by CoDanny** [comment]
This doesn't seem to override what's already in the printer-profile.yaml file. Also it doesn't take into account a setting that the manufacturer can decide if the user is allowed to modify these values or not.

**Comment by julianCast** [comment]
The way it is now, the printer profile specified inside the manufacturer pkg will only be used if printer-profile.yaml file doesn't exists yet.

Do you want to check every time the box is booted to update existing config ?

**Comment by CoDanny** [comment]
No, there's no need. Does this ensure that the box starts with the configuration specified in the manufacturer package and that it can't be changed by the user if the manufacturer doesn't want to?

**Comment by julianCast** [comment]
Now it's fixed:
- Manufacturer can now specify if they allow to edit its presets. 
Parameter _temperature_presets_edit_ is True by default.

**Comment by CoDanny** [comment]
Send it again when the changes we talked about are done

**Pull request closed without merging**
